worker_processes 1;
pid /var/run/nginx.pid;
error_log /dev/stderr warn;
events { worker_connections 128; }
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log off;
    sendfile on;
    tcp_nopush on;
    keepalive_timeout 15s;
    send_timeout 15m;
    client_header_timeout 10s;
    client_body_timeout 10s;
    client_max_body_size 1k;
    server_tokens off;
    resolver 127.0.0.11 valid=10s ipv6=off;
    resolver_timeout 5s;
    limit_conn_zone $binary_remote_addr zone=per_client:1m;
    limit_req_zone $binary_remote_addr zone=api_rate:1m rate=10r/s;
    include /etc/nginx/conf.d/*.conf;
}

